### ISSUE TITLE
Cannot resolve some ui-router states with the current app structure

### ISSUE THREAD

**Issue by hussaintamboli** [STUkh/generator-angular-webpack-es6#12]
I have below states in my app

    login (from /pages/login/login.route.js)
    app (abstract) (from /components/header/header.route.js)
    app.upload(abstract)  (from /pages/upload/upload.route.js)
    app.upload.products   (from /pages/upload/products/products.route.js)

And my index.module.js includes the all the page modules

    const App = angular.module(
        "CMS", [
             require('angular-ui-router'),
             require('angular-ui-bootstrap'),

             // core
             require("./core/core.module").name,

             // components
             require("./index.components").name,

             // routes
             require("./index.routes").name,

             // pages
             require("./pages/login/login.module").name,
             require("./pages/upload/upload.module").name,
             require("./pages/upload/products/products.module").name
        ]
    );

In LoginController I am redirecting to `app.upload.products` on successful login to api call. 

    $state.go('app.upload.products');

But I get an error saying
    
    Could not resolve 'app.upload.products' from state 'login'

Why is this state getting resolved? What did I miss?

**Comment by STUkh** [comment]
Check your route params, check that products module loaded properly as dependency of your upload module or main application module. Seems that you miss module initialization, try debug it.

**Comment by hussaintamboli** [comment]
Could you please point me in the right direction for Module Initialization?

I tried including product.module dependency in upload.module

```
//upload.module.js
...
const uploadContentPageModule = angular.module('upload-content', [
  'ui.router', require("./products/products.module").name
]);
...
```

and removed it from index.module.js

```
// pages
const App = angular.module(
  "CMSMd", [
  ...
  require("./pages/login/login.module").name,
  require("./pages/upload-content/upload-content.module").name
  ....
]
```

But I still get an error saying 

```
angular.js:13923 Error: Could not resolve 'app.upload.catalog' from state 'login'
```

**Comment by STUkh** [comment]
Show me your routes. Or share full example of your code, i'll try to help

**Comment by hussaintamboli** [comment]
I can't upload my project on github. But I'll share my routes and modules which should be enough to understand the issue.

The main `abstract` state is in /header component

**/components/header/header.route.js**

```
'use strict';

import headerTpl from './header.html';

function routeConfig($stateProvider) {
  'ngInject';

  $stateProvider
    .state('app', {
      url: '',
      template: '<ui-view></ui-view>',
      abstract: true
    });

}

export default routeConfig;
```

**/components/header/header.module.js**

```
// ....
import route from './header.route';
const headerModule = angular.module('header-module', [
  'ui.router'
]);

headerModule
  .config(route);

export default headerModule;
```

**/index.components.js**

```
'use strict';

export default angular.module('index.components', [
  require('./components/header/header.module').name,
  require('./components/footer/footer.module').name
]);
```

**/pages/login/login.route.js**

```
'use strict';

import loginTpl from './login.html';

function routeConfig($stateProvider) {
  'ngInject';

  $stateProvider
    .state('login', {
      url: '/login',
      templateUrl: loginTpl,
      controller: require('./login.controller'),
      controllerAs: 'loginCtrl'
    });
}

export default routeConfig;
```

**/pages/login/login.module.js**

```
import route from './login.route';

const loginPageModule = angular.module('login-module', [
    'ui.router'
]);

loginPageModule
  .config(route);

export default loginPageModule;
```

Similarly,

**/pages/upload/upload.route.js**

```
abstract 'app.upload' is defined
```

**/pages/upload/upload.module.js**

```
'use strict';

const uploadContentPageModule = angular.module('upload-content', [
  'ui.router', require('./products/products.module').name
]);
```

**/pages/upload/products/products.route.js**

```
app.upload.products is defined
```

and finally,

**/index.module.js**

```
'use strict';

import * as components from './index.components';
import config from './index.config';
import run from './index.run';


const App = angular.module(
  "App", [
    // plugins
    require('angular-ui-router'),
    require('angular-ui-bootstrap'),

    // core
    require("./core/core.module").name,

    // components
    require("./index.components").name,

    // routes
    require("./index.routes").name,

    // pages
    require("./pages/login/login.module").name,
    require("./pages/upload/upload.module").name

  ]
);

App
  .config(config)
  .run(run);

export default App;
```

Hope you replicate the issue.

**Comment by STUkh** [comment]
Be sure you have export and require of /pages/upload/upload.module.js

Because you have nothing in require("./pages/upload-content/upload-content.module").name or you miss upload.module.js

**Comment by hussaintamboli** [comment]
Actually the import is correctly imported in /index.module.js. 

There is a correction in the snippet above. I have updated it.

Everything is in place then what's wrong?

**Comment by STUkh** [comment]
Share full example with this problem. Or send me on email: stukak@gmail.com

**Comment by hussaintamboli** [comment]
I have sent you an example.

**Comment by hussaintamboli** [comment]
Hey, Did you find time to look at the code?

**Comment by STUkh** [comment]
Just find your email in spam folder... looked into your code an found mistake: you have 2 different modules with same name 'upload-content'. Rename one of them into 'upload-content-catalog' and everything will be fine.

http://joxi.ru/zANy75PtBBNYx2

http://joxi.ru/BA0Mq4XHJJdedr
