### ISSUE TITLE
Unable to add logo image in html template file

### ISSUE THREAD

**Issue by basav22** [STUkh/generator-angular-webpack-es6#16]
Hi,

I have used this yeomen generator and am naive to Webpack and trying to use image in /assets/images folder (logo.png). 

I see configuration of webpack - 

    // resolves modules
    resolve: {
      extensions: ['.js', '.es6', '.jsx', '.scss', '.css'],
      alias: {
        _appRoot: path.join(_path, 'src', 'app'),
        _images: path.join(_path, 'src', 'app', 'assets', 'images'),
        _stylesheets: path.join(_path, 'src', 'app', 'assets', 'styles'),
        _scripts: path.join(_path, 'src', 'app', 'assets', 'js')
      }
    },`

So I have below code in my controller - 

    const logo = require('../../assets/images/logo.png');

But webpack is unable to find logo.png module. I don't understand alias defined in webpack.config file and how we use it in our source code?

**Comment by STUkh** [comment]
Hello, just published update version 1.0.0. Thx for your issue, there was mistake in alias path, but you should check you image path, because i think you should have "../../../" there. Now i recommend just use "_images" alias  and import like:
``` import logo from "_images/logo.png"; ```
Also i've added examples with images to main page.

**Comment by basav22** [comment]
Hello,

Thank you.Solved the problem. Alias and image url-loader was causing the problem.

But as I see the latest release docs, webpack is updated and other changes are made. If I have to get those all changes, what needs to be done? I have already generated code from older version 0.5.0. Now I need to update to 1.0.0. Whether I have to install updated generator and move code there ?

**Comment by STUkh** [comment]
I strongly recommend to upgrade to 1.0.0,  as migration note: 
* replace all require statements with imports
* in async loaded modules add prefix .default. AsyncModule.name -> AsyncModule.default.name
* Replace buggy old webpack hack syntax "import * as X from './module'" -> "import X from './module'"

That's all, but you will get the latest webpack works.
