### ISSUE TITLE
Getting 404 Not Found error for templateUrl on $uibModal

### ISSUE THREAD

**Issue by hussaintamboli** [STUkh/generator-angular-webpack-es6#18]
My app is structured like this,

![scaffolding](https://cloud.githubusercontent.com/assets/2324958/25087528/373abc60-238d-11e7-867a-3b6fd93f1baf.png)

I am calling below function from **src.controller.js** on ng-click of a button.

```
vm.updateSourceAndVisibility = function(skus) {
  $log.info("In updateSourceAndVisibility");
  var modal = $uibModal.open({
    animation: true,
    templateUrl: require('./source-selection/source.selection.html'),
    controller: require('./source-selection/source.selection.controller.js'),
    controllerAs: 'sourceSelectCtrl',
    backdrop : 'static',
    size: 'md'
  });
};
```

But I get `404 Not Found` error for `http://localhost:8080/src/app/pages/src/selection/selection.html`. 

How do I show my UI from source.selection.html on the modal?

I have tried using `template` as well instead of `templateUrl`.

    template: require('./selection/selection.html'),

In this case, modal gets opened with below text,

    /src/app/pages/src/selection/selection.html

**Comment by hussaintamboli** [comment]
To go forward for now, I set the whole HTML from selection.html to template. Now I can see some UI. But now I see that controller is also not working.

For e.g. I am calling below function on ng-click of close button,

    function _close() {
      $uibModalInstance.dismiss('cancel');
    }

But it's not closing the modal. I don't think selection.controller.js is getting loader either.

**Comment by STUkh** [comment]
You should require or import your template higher in top-level declarations, because when webpack build templateCache it doesn't know about this template, so you should pre-cache it and then use, like this:

```
var sourceSelectionTpl = require('./source-selection/source.selection.html');
vm.updateSourceAndVisibility = function(skus) {
  var modal = $uibModal.open({
    templateUrl: sourceSelectionTpl ,
    controller: require('./source-selection/source.selection.controller.js'),
  });
};
```

**Comment by hussaintamboli** [comment]
Tried what you suggested. But It's not working.

**Comment by hussaintamboli** [comment]
I solved it by creating selection.module.js in selection/ and importing selection.html there.

```
'use strict';

import sourceSelectionCnst from './selection.constant';
import sourceSelectionTpl from './selection.html';

const sourceSelectionModule = angular.module('src-selection', [
]);

sourceSelectionModule
    .constant('sourceSelectionCnst', sourceSelectionCnst);

export default sourceSelectionModule;

```

I had to also import it in my controller 

`import sourceSelectionTpl from './selection/selection.html';`

Then I was able to use templateUrl

`templateUrl: sourceSelectionTpl,`

This solves the issue but I am not sure whether importing the template twice will load the template twice. Please suggest another better way if any.

**Comment by STUkh** [comment]
Better way i described in previous message. Just import template not in modal config object or function. 
In your second case it will not be loaded twice, because it cached by name in $templateCache service

**Comment by hussaintamboli** [comment]
Okay. Got it. Thanks.

**Comment by Alex-DE-74** [comment]
Have exactly the same problem. Tried all internet tipps down and up since one week - no solution.
Tried you solution and it is not working on **angular-cli on windows** with webpack, error say that **'require'** is _not defined_.
How you get this working, please?
