### ISSUE TITLE
How change the developer server from 8080 ??

### ISSUE THREAD

**Issue by QadMohKuwait** [STUkh/generator-angular-webpack-es6#28]
The application server starts with localhost:8080, this port is currently used by wamp server and need to change it

**Comment by STUkh** [comment]
Hey! Use "port" option in webpack development config or host argument in package.json file in development script with desirable value

A few examples you can find in webpack documebtation, or this article: https://stackoverflow.com/questions/33272967/how-to-make-the-webpack-dev-server-run-on-port-80-and-on-0-0-0-0-to-make-it-publ
