### ISSUE TITLE
Source Map not getting generated and Build stuck at 92% UglifyJSPlugin

### ISSUE THREAD

**Issue by anugoyal12** [STUkh/generator-angular-webpack-es6#32]
We have upgraded to Angular 6 last week. We are not able to see Source Map in Debug Console. Our Build gets stuck at 92% UglifyJSPlugin. Please let me know if anyone else is having this issue. Is this a bug in Angular6? How to fix this issue? I would really appreciate any guidance.

Regards
Anu

**Comment by STUkh** [comment]
This project based on angularjs 1.x branch
