### ISSUE TITLE
"Failed to instantiate module ng"

### ISSUE THREAD

**Issue by filipepratalima** [STUkh/generator-angular-webpack-es6#7]
When I create a new project with only default options, when running `npm run dev` I get the following error in the Chrome console and nothing is displayed.

> Uncaught Error: [$injector:modulerr] Failed to instantiate module ng due to:
> Error: [$injector:strictdi] function($provide) is not using explicit annotation and cannot be invoked in strict mode
> http://errors.angularjs.org/1.5.8/$injector/strictdi?p0=function(%24provide)
>     at http://localhost:8080/vendor.js:13298:13
>     at Function.annotate [as $$annotate](http://localhost:8080/vendor.js:17182:18)
>     at injectionArgs (http://localhost:8080/vendor.js:17909:37)
>     at Object.invoke (http://localhost:8080/vendor.js:17940:19)
>     at runInvokeQueue (http://localhost:8080/vendor.js:17841:36)
>     at http://localhost:8080/vendor.js:17850:12
>     at forEach (http://localhost:8080/vendor.js:13551:21)
>     at loadModules (http://localhost:8080/vendor.js:17831:6)
>     at createInjector (http://localhost:8080/vendor.js:17753:20)
>     at doBootstrap (http://localhost:8080/vendor.js:14988:21)
> http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=ng&p1=Error%3A%20%5…at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A8080%2Fvendor.js%3A14988%3A21)

**Comment by STUkh** [comment]
Just reinstalled project with all default options and everything seems to work smooth. Please, re-check your npm install log. If you have any weird errors, try to follow [this](https://github.com/nodejs/node-gyp) guide to fix node's platform-specific errors, especially on windows. 

_Error: [$injector:strictdi]_ means that some module wasn't annotated by ng-annotate loader and in strict mode angular throws error. You can try to set "strictDi: false" in "index.bootstrap.js" file, but it's not production-ready solution.
