### ISSUE TITLE
Need help in doing unit testing

### ISSUE THREAD

**Issue by hussaintamboli** [STUkh/generator-angular-webpack-es6#9]
I have created `index.test.js`

```
var testsContext = require.context(".", true, /\.spec.js$/);
testsContext.keys().forEach(testsContext);
```

and configured it in karma.config.js 

```
files: [
    'src/app/index.test.js'
],
preprocessors: {
  'src/app/index.test.js': ['webpack']
},
```

The sample test that I created

```
import app from 'src/app/index.module.js';

describe('app', () => {

  describe('MainController', () => {
    let ctrl;

    beforeEach(() => {
      angular.mock.module(app);

      angular.mock.inject(($controller) => {
       ctrl = $controller('MainController', {});
      });
    });

    it('should contain the starter url', () => {
      expect(ctrl.test).toBe('test');
    });
  });
});
```

But when I run it with

```
npm run test --verbose
```

It says 

```
echo 'Error: no test specified'
```

and when I runt it with

```
node_modules/karma-cli/bin/karma start karma.conf.js --single-run
```

It says

```
Chrome 52.0.2743 (Linux 0.0.0) ERROR
Uncaught SyntaxError: Unexpected token import
```

How do I go about doing unit testing here? Please help.

**Comment by STUkh** [comment]
> echo 'Error: no test specified'
- this because you haven't such task in packages.json file.

> Uncaught SyntaxError: Unexpected token import

Are you sure you have imports syntax?
Which version of nodejs do you use?

**Comment by hussaintamboli** [comment]
Added 

```
cross-env NODE_ENV=development ./node_modules/karma/bin/karma start --single-run=true
```

to package.json so 1 is fixed.

```
Uncaught SyntaxError: Unexpected token import
at src/app/index.vendor.js:4
```

error is still there. I am using v6.9.1 nodejs

**Comment by STUkh** [comment]
I think you need [karma-babel-preprocessor](https://github.com/babel/karma-babel-preprocessor) to transpile your code. This case also described in [babel setup page](https://babeljs.io/docs/setup/#installation)

**Comment by hussaintamboli** [comment]
It fixed it. Thanks. But now I get another error

Added it. 

```
npm i -D karma-babel-preprocessor
```

and put it in karma.conf.js

```
plugins: [
    ....
    'karma-babel-preprocessor'
]
```

The test doesn't run

```
Uncaught ReferenceError: require is not defined
at src/app/index.vendor.js:5 
```

**Comment by hussaintamboli** [comment]
I tried `karma-browserify` but it didn't work.

http://stackoverflow.com/a/30781687/1637867

**Comment by STUkh** [comment]
Try to setup your babelPreprocessor object from karma.conf.js with settings like in .babelrc file

**Comment by hussaintamboli** [comment]
Updated it

```
babelPreprocessor: {
  options: {
    presets: ['es2017'],
    sourceMap: 'inline'
  }
} 
```

Still gettting the same error

```
Uncaught ReferenceError: require is not defined
at src/app/index.vendor.js:5
```

**Comment by hussaintamboli** [comment]
I figured out that I need to include some plugins in babelPreprocessor.

```
plugins: ['transform-es2015-modules-umd'],
```

so the error `require is not defined` went away. But I get a new error

```
Uncaught ReferenceError: angular is not defined
at src/app/index.bootstrap.js:19
```

With few trial and errors, this error went away when I included `transform-es2015-modules-amd`. Then I am getting a new error.

```
Uncaught ReferenceError: define is not defined
```

If I get a good resource where I can figure things out myself, it will be great.

**Comment by STUkh** [comment]
Try to follow this guide, it may help: http://mike-ward.net/2015/09/07/tips-on-setting-up-karma-testing-with-webpack/

**Comment by hussaintamboli** [comment]
That's good. I did exactly like that. But I think the link is referring a different directory structure whereas `generator-angular-webpack-es6` created a different directory structure

I am getting this

```
31 10 2016 13:03:16.038:ERROR [karma]: { Error: no such file or directory
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
code: 'ENOENT',
errno: 34,
message: 'no such file or directory',
path: '/_karma_webpack_/src/app/index.bootstrap.js' }
```

I think that's because my webpack.config.js is modularised into 

```
config/webpack/global.js
config/webpack/environments/development.js
```

How do I tackle this? Why is it appending '/_karma_webpack_/'?

**Comment by STUkh** [comment]
You also can try karma config from this [example](https://github.com/MichalZalecki/angular-lazyload-webpack)

**Comment by hussaintamboli** [comment]
Yes. This worked! Thanks.
